### ISSUE TITLE
Licensing & patent risks

### ISSUE THREAD

**Issue by davelab6** [typetura/typetura.js#13]
https://typetura.com says

> **Patent Policy**
> 
> This interface, specifically the keyframe/breakpoint markers and how they are manipulated is patent pending in the United States Patent Office

While https://github.com/typetura/typetura.js is licensed under the MIT license, that includes no language on patents. 

Is the code in this repo free of patent risks, or is this project similar to old Facebook React where the code is nominally under a libre license, but not really because there is a patent in the background? 

If this repo was under a license that includes language on patents (e.g. Apache 2.0, or GNU (L)GPL, or Mozilla MPL) that would clarify the situation :)

**Comment by scottkellum** [comment]
The JS is MIT licensed and free of patents. The patent filed is around how the interface works on the website (the GUI for keyframe behavior and having that tied to page width) and does not include this open source project.

I made a split between interface (closed source, design patent) and JS engine (open source)

Hope that helps and thank’s for noting this

**Comment by davelab6** [comment]
Great! I was unsure about `how they are manipulated` :) Perhaps I could suggest changing,

> manipulated is patent pending in the United States Patent Office

to

> manipulated is design patent pending in the United States Patent Office

**Comment by scottkellum** [comment]
👍 good suggestion thank you!
