### ISSUE TITLE
transition doesnt work on Safari 12.0.1

### ISSUE THREAD

**Issue by TBD** [typetura/typetura.js#16]
Safari 12.0.1 / macOS 10.4.1

**steps:**
1. add 0.5em in font-size (keyframe created - lighting bolt and code is visible)
2. move viewport slider to the right
3. add 2em in font-size (keyframe created - lighting bolt and code is visible)
4. move viewport slider to see the transition

**result:** no changes in font-size
**expected:** smooth transition in font-size ( works in Chrome)

**Comment by scottkellum** [comment]
Thanks for the issue and sorry for the delay! I think I see the problem and will address it tonight.

**Comment by scottkellum** [comment]
Fix coming shortly to typetura.com. The JS is safe to use.

The issue is that Safari seems to not re-render animations on elements so when you make any value change on typetura.com, that change isn’t registered by the browser. The fix is to clear the typetura animation settings on input change.

**Comment by scottkellum** [comment]
fixed
