### ISSUE TITLE
Typetura stopped working

### ISSUE THREAD

**Issue by samueljudd** [typetura/typetura.js#25]
Typetura has stopped working on my projects and on the demo you guys have: https://typetura-js.netlify.com/. However, on your guy's website, everything seems to be working fine.

It was working fine two days before. Has anything changed?

I've tested it on Chrome (79.0.3945.117), Firefox (72.0.1), Safari (13.0.4) both windows and mac.

**Comment by scottkellum** [comment]
Thanks for the heads up! Is it working for you now?

I’m very sorry for this issue.

**Comment by samueljudd** [comment]
Hi Scott,

Yes! It’s working now. I’ve updated to the latest version and it’s all good to go.


Thanks!
Samuel Judd
